# image:
image: genshen/pkg:0.4.1-clang10-mpi

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - vendor/

stages:
  - fetch
  - build

fetch:
  stage: fetch
  image:
    name: genshen/pkg:0.4.1-clang10-mpi
    entrypoint: [ "" ]
  tags:
    - cpp
    - mpi
  script:
    - pkg fetch
    - pkg install
  artifacts:
    untracked: true

build:
  stage: build
  image:
    name: genshen/pkg:0.4.1-clang10-mpi
    entrypoint: [ "" ]
  tags:
    - cpp
    - mpi
  script:
    - cmake -Bcmake-build -DCMAKE_BUILD_TYPE=Debug -H.
    - make -Ccmake-build
  # artifacts:
    # untracked: true
  dependencies:
    - fetch
